services:
  db:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: postgres:latest
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bite_balance
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
      - ./Food-Data:/food-data

volumes:
  pgdata:
